#### Python types
In python you can declare variables without specifying the type of data it is going to hold.
Python is a dynamically typed language. 

Duck typing: If it walks like a duck and quacks like a duck, then it must be a duck.

REMEMBER: Type hinting is a way to specify the type of the variable. It is not enforced by the interpreter. 

In [1]:
from typing import Final

COURSE_NAME: Final[str] = "CMPS446"
var_one: int = 3
var_two: bool = True
var_three: str = "Hello World"
print(var_one, var_two, var_three)
var_four: str = "your favv TA"
print(f"{COURSE_NAME}: {var_three}, by {var_four}.")

3 True Hello World
CMPS446: Hello World, by your favv TA.


#### Managing Paths in Python

In [2]:
import os
from pathlib import Path 

BASE_PATH: Final[Path] = Path().resolve()
DATA_PATH: Final[Path] = os.path.join(BASE_PATH, 'data')
print(f"BASE_PATH: {BASE_PATH}")
print(f"DATA_PATH: {DATA_PATH}")

BASE_PATH: /Users/ziadh/Desktop/playgroud/image-processing/cmps446/src/lab-one/lab-one-std
DATA_PATH: /Users/ziadh/Desktop/playgroud/image-processing/cmps446/src/lab-one/lab-one-std/data


#### Printing in Python

In [3]:
"""Printing to file in Python
Example logging to a file
"""
log_file_path: Final[Path] = os.path.join(BASE_PATH, "output", "output.log")

def log_to_file(file_path: Path, message: str) -> None:
    with open(file_path, "w") as f:
        import datetime
        timestamp: datetime = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        log_message: str = f"[{timestamp}] {message}"
        print(log_message, file=f)

log_to_file(log_file_path, "Hello World!")

#### Basics of division in Python

In [4]:
# division in python
print(5/2)

# floor division or integer division
print(5 // 2)

2.5
2


#### Looping in Python

In [5]:
array: list[int] = [1, 2, 3, 4, 5]

for num in array:
    print(num)

for i in range(5):
    print(i)

# range(start, stop, step)
for i in range(0, 1_000_000, 10_000):
    print(f"{i:,}")

for num in array:
    if num%2 == 0:
        print(num)

# Usage of list comprehension
even_items: list[int] = [num for num in array if num%2 == 0]
print(even_items)
print(*even_items)
print(*even_items, sep=', ')

1
2
3
4
5
0
1
2
3
4
0
10,000
20,000
30,000
40,000
50,000
60,000
70,000
80,000
90,000
100,000
110,000
120,000
130,000
140,000
150,000
160,000
170,000
180,000
190,000
200,000
210,000
220,000
230,000
240,000
250,000
260,000
270,000
280,000
290,000
300,000
310,000
320,000
330,000
340,000
350,000
360,000
370,000
380,000
390,000
400,000
410,000
420,000
430,000
440,000
450,000
460,000
470,000
480,000
490,000
500,000
510,000
520,000
530,000
540,000
550,000
560,000
570,000
580,000
590,000
600,000
610,000
620,000
630,000
640,000
650,000
660,000
670,000
680,000
690,000
700,000
710,000
720,000
730,000
740,000
750,000
760,000
770,000
780,000
790,000
800,000
810,000
820,000
830,000
840,000
850,000
860,000
870,000
880,000
890,000
900,000
910,000
920,000
930,000
940,000
950,000
960,000
970,000
980,000
990,000
2
4
[2, 4]
2 4
2, 4


### Array Indexing

In [6]:
array: list[int] = [0, 1, 2, 3, 4, 5]
print(array[:3])

import numpy as np

second_array: np.ndarray[int] = np.array(array)
third_array: np.ndarray[int] = np.copy(second_array)

print(third_array)
third_array[:3] = 0
print(third_array)

third_array: np.ndarray[int] = np.copy(second_array)
third_array[third_array%2==0] = -1
print(third_array)

third_array: np.ndarray[int] = np.copy(second_array)
third_array[(third_array%2==0) & (third_array==2)] = -1
print(third_array)

[0, 1, 2]
[0 1 2 3 4 5]
[0 0 0 3 4 5]
[-1  1 -1  3 -1  5]
[ 0  1 -1  3  4  5]


In [7]:
original_matrix: np.ndarray[list[int]] = np.array([
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5]
])

copied_matrix: np.ndarray[list[int]] = np.copy(original_matrix)
print(copied_matrix)

copied_matrix[1:3, 1:3] = 0
print(copied_matrix)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4 5]
 [1 0 0 4 5]
 [1 0 0 4 5]]


#### Generate NumbPy arrays

In [8]:
zeros_array: np.ndarray[int] = np.zeros(shape=(6, 5), dtype=int)
ones_array: np.ndarray[int] = np.ones(shape=(6, 5), dtype=int)

print(zeros_array)
print(ones_array)
print(ones_array.shape)
print(ones_array.shape[0])

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
(6, 5)
6


#### Positional and Keyword arguments

In [9]:
def fun(x: int, y: int, z: int) -> None:
    print(x, y, z)
    
fun(1, 2, 3)
fun(x=1, y=2, z=3)

1 2 3
1 2 3


In [10]:
from typing import Optional

x: Optional[int] = None
print('x is None' if x is None else 'x is not None')

x is None


#### Convert unit8 images to range 0-1

In [11]:
import numpy as np

# Create a sample uint8 image
uint8_image = np.array([
    [100, 200, 50],
    [25, 150, 75],
    [0, 255, 30]
], dtype=np.uint8)

# Normalize the uint8 image to the range [0, 1]
normalized_image = uint8_image / uint8_image.max()

print(normalized_image)

[[0.39215686 0.78431373 0.19607843]
 [0.09803922 0.58823529 0.29411765]
 [0.         1.         0.11764706]]
